.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH seednaut-list 1  "list " 
.SH NAME
seednaut\-list \- List available snapshots
.SH SYNOPSIS
\fBseednaut list\fR <\fIPATH\fR> [\fISNAPSHOTS\fR] 
.SH DESCRIPTION
List available snapshots
.SH OPTIONS
.TP
<\fIPATH\fR>
The input path (snapshot file or directory)
.TP
[\fISNAPSHOTS\fR]
Indices of snapshots to target. If omitted, all snapshots are targeted
